version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - test-netcore:
          name: .NET Core 3.1
          docker-image: mcr.microsoft.com/dotnet/core/sdk:3.1-focal
          build-target-framework: netcoreapp3.1
          test-target-framework: netcoreapp3.1
      - test-netcore:
          name: .NET 6.0
          docker-image: mcr.microsoft.com/dotnet/sdk:6.0-focal
          build-target-framework: net6.0
          test-target-framework: net6.0
      - test-windows-netframework:
          name: .NET Framework 4.6.2
          test-target-framework: net462

orbs:
  win: circleci/windows@1.0.0

jobs:
  test-netcore:
    parameters:
      docker-image:
        type: string
      build-target-framework:
        type: string
      test-target-framework:
        type: string
    docker:
      - image: <<parameters.docker-image>>
    environment:
      ASPNETCORE_SUPPRESSSTATUSMESSAGES: true
      BUILDFRAMEWORKS: <<parameters.build-target-framework>>
      TESTFRAMEWORK: <<parameters.test-target-framework>>
    steps:
      - checkout
      - run:
          name: install project dependencies
          command: dotnet restore
      - run:
          name: build
          command: dotnet build src/LaunchDarkly.InternalSdk
      - run:
          name: run tests
          command: |
              dotnet test \
              -l "junit;LogFilePath=/tmp/circle-reports/unit-tests-commonsdk.xml" \
              -f <<parameters.test-target-framework>> \
              test/LaunchDarkly.InternalSdk.Tests/LaunchDarkly.InternalSdk.Tests.csproj
      - store_test_results:
          path: /tmp/circle-reports

  test-windows-netframework:
    parameters:
      test-target-framework:
        type: string
    executor:
      name: win/vs2019
      shell: powershell.exe
    environment:
      ASPNETCORE_SUPPRESSSTATUSMESSAGES: true
      BUILDFRAMEWORKS: net462
      TESTFRAMEWORK: <<parameters.test-target-framework>>
    steps:
      - checkout
      - run:
          name: install project dependencies
          command: dotnet restore
      - run:
          name: build
          command: dotnet build src/LaunchDarkly.InternalSdk -f net462
      - run:
          name: run tests
          command: |
              dotnet test \
              -l "junit;LogFilePath=/tmp/circle-reports/unit-tests.xml" \
              test/LaunchDarkly.InternalSdk.Tests/LaunchDarkly.InternalSdk.Tests.csproj
      - store_test_results:
          path: /tmp/circle-reports
