version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - test-netcore:
          name: .NET Standard 2.0 + .NET Core 2.0
          docker-image: microsoft/dotnet:2.0-sdk-jessie
          build-target-framework: netstandard2.0
          test-target-framework: netcoreapp2.0
      - test-netcore:
          name: .NET Core 2.1
          docker-image: mcr.microsoft.com/dotnet/core/sdk:2.1-focal
          build-target-framework: netcoreapp2.1
          test-target-framework: netcoreapp2.1
      - test-netcore:
          name: .NET Core 3.1
          docker-image: mcr.microsoft.com/dotnet/core/sdk:3.1-focal
          build-target-framework: netcoreapp2.1
          test-target-framework: netcoreapp3.1
      - test-netcore:
          name: .NET 5.0
          docker-image: mcr.microsoft.com/dotnet/sdk:5.0-focal
          build-target-framework: net5.0
          test-target-framework: net5.0
      - test-windows-netframework-4-5-2:
          name: .NET Framework 4.5.2

orbs:
  win: circleci/windows@1.0.0

jobs:
  test-netcore:
    parameters:
      docker-image:
        type: string
      build-target-framework:
        type: string
      test-target-framework:
        type: string
    docker:
      - image: <<parameters.docker-image>>
    environment:
      ASPNETCORE_SUPPRESSSTATUSMESSAGES: true
      BUILDFRAMEWORKS: <<parameters.build-target-framework>>
      TESTFRAMEWORK: <<parameters.test-target-framework>>
    steps:
      - checkout
      - run:
          name: install project dependencies
          command: dotnet restore
      - run:
          name: build
          command: dotnet build src/LaunchDarkly.InternalSdk
      - run:
          name: run tests
          command: dotnet test test/LaunchDarkly.InternalSdk.Tests/LaunchDarkly.InternalSdk.Tests.csproj -f <<parameters.test-target-framework>>

  test-windows-netframework-4-5-2:
    executor:
      name: win/vs2019
      shell: powershell.exe
    environment:
      ASPNETCORE_SUPPRESSSTATUSMESSAGES: true
      BUILDFRAMEWORKS: net452
      TESTFRAMEWORK: net46 # we build for 4.5.2, but we run in 4.6 so we can use some test libraries that don't work in 4.5
    steps:
      - checkout
      - run:
          name: install project dependencies
          command: dotnet restore
      - run:
          name: build
          command: dotnet build src/LaunchDarkly.InternalSdk -f net452
      - run:
          name: run tests
          command: dotnet test test/LaunchDarkly.InternalSdk.Tests/LaunchDarkly.InternalSdk.Tests.csproj -f net46
