version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - test-netcore-2-1
      - test-windows-netframework-4-5-2

orbs:
  win: circleci/windows@1.0.0

jobs:
  test-netcore-2-1:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1-focal
    environment:
      ASPNETCORE_SUPPRESSSTATUSMESSAGES: true
      TESTFRAMEWORK: netcoreapp2.1
    steps:
      - checkout
      - restore_cache:
          keys: 
            - netcore21-deps-{{ checksum "src/LaunchDarkly.InternalSdk/LaunchDarkly.InternalSdk.csproj" }}-{{ checksum "test/LaunchDarkly.InternalSdk.Tests/LaunchDarkly.InternalSdk.Tests.csproj" }}
      - run:
          name: install project dependencies
          command: dotnet restore
      - save_cache:
          key: netcore21-deps-{{ checksum "src/LaunchDarkly.InternalSdk/LaunchDarkly.InternalSdk.csproj" }}-{{ checksum "test/LaunchDarkly.InternalSdk.Tests/LaunchDarkly.InternalSdk.Tests.csproj" }}
          paths:
            - /root/.nuget/packages
      - run:
          name: build
          command: dotnet build src/LaunchDarkly.InternalSdk -f netstandard2.0
      - run:
          name: run tests
          command: dotnet test test/LaunchDarkly.InternalSdk.Tests/LaunchDarkly.InternalSdk.Tests.csproj -f netcoreapp2.1

  test-windows-netframework-4-5-2:
    executor:
      name: win/vs2019
      shell: powershell.exe
    environment:
      ASPNETCORE_SUPPRESSSTATUSMESSAGES: true
      TESTFRAMEWORK: net46 # we build for 4.5.2, but we run in 4.6 so we can use some test libraries that don't work in 4.5
    steps:
      - checkout
      - restore_cache:
          keys: 
            - net452-deps-{{ checksum "src/LaunchDarkly.InternalSdk/LaunchDarkly.InternalSdk.csproj" }}-{{ checksum "test/LaunchDarkly.InternalSdk.Tests/LaunchDarkly.InternalSdk.Tests.csproj" }}
      - run:
          name: install project dependencies
          command: dotnet restore
      - save_cache:
          key: net452-deps-{{ checksum "src/LaunchDarkly.InternalSdk/LaunchDarkly.InternalSdk.csproj" }}-{{ checksum "test/LaunchDarkly.InternalSdk.Tests/LaunchDarkly.InternalSdk.Tests.csproj" }}
          paths:
            - C:\Users\circleci\.nuget\packages
      - run:
          name: build
          command: dotnet build src/LaunchDarkly.InternalSdk -f net452
      - run:
          name: run tests
          command: dotnet test test/LaunchDarkly.InternalSdk.Tests/LaunchDarkly.InternalSdk.Tests.csproj -f net46
