version: 2

publications:
  - url: https://nuget.org/packages/LaunchDarkly.InternalSdk
    description: NuGet

branches:
  - name: main
  - name: 2.x

jobs:
  - docker: {}
    template:
      name: dotnet6-linux
    env:
      LD_RELEASE_TEST_TARGET_FRAMEWORK: net6.0
      LD_RELEASE_DOCS_TARGET_FRAMEWORK: netstandard2.0
