version: 2

repo:
  public: dotnet-sdk-internal
  private: dotnet-sdk-internal-private

publications:
  - url: https://nuget.org/packages/LaunchDarkly.InternalSdk
    description: NuGet

jobs:
  - docker: {}
    template:
      name: dotnet-linux
    env:
      LD_RELEASE_TEST_TARGET_FRAMEWORK: net50
      LD_RELEASE_DOCS_TARGET_FRAMEWORK: netstandard2.0
