repo:
  public: dotnet-sdk-internal
  private: dotnet-sdk-internal-private

publications:
  - url: https://nuget.org/packages/LaunchDarkly.InternalSdk
    description: NuGet

circleci:
  windows:
    context: org-global

template:
  name: dotnet-windows
  env:
    LD_RELEASE_TEST_TARGET_FRAMEWORK: net452
    LD_RELEASE_DOCS_TARGET_FRAMEWORK: net452
